services:
  maxbloglite:
    build: .
    ports:
      - "8000:80"
    restart: unless-stopped
    volumes:
      - ${CONTENT_FOLDER}./articles:/usr/local/app/articles
      - ${CONTENT_FOLDER}./private:/usr/local/app/private